import Head from 'next/head'

import { Wrapper } from '@styles/global'

export default function Home() {
  return (
    <Wrapper>
      <div className={'container'}>
        <Head>
          <title>Boilerplate Next Typescript</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={'main'}>
          <h1 className={'title'}>Welcome</h1>
          <p className={'description'}>
            Get started by editing <code className={'code'}>pages/index.js</code>
          </p>

          <div className={'grid'}>
            <a href="https://nextjs.org/docs" className={'card'}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={'card'}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/master/examples"
              className={'card'}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={'card'}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>
      </div>
    </Wrapper>
  )
}
